const stories: Record<string,{category:string,title:string,excerpt:string,body:string[]}> = {
"the-internets-biggest-stories-and-ideas-in-one-place":{category:"Trending",title:"The internet's biggest stories and ideas in one place",excerpt:"Discover fresh stories, useful guides, technology updates and entertaining content every day.",body:["The internet is a huge place for discovering ideas, learning practical skills, and keeping up with culture. A thoughtful mix of trusted sources can make that experience more useful.","When a topic is moving quickly, check the publication date and look for primary sources before sharing claims. For evergreen topics, save clear guides that you can return to later."]},
"smart-tools-that-can-make-everyday-work-easier":{category:"Technology",title:"Smart tools that can make everyday work easier",excerpt:"Simple technology tips, apps and digital tools worth trying.",body:["Digital tools can simplify repetitive tasks, but the most useful setup is often the one that stays easy to maintain.","Start by identifying a recurring task, then try one tool that solves that specific need. Review permissions and privacy settings before connecting accounts or uploading personal information."]},
"small-habits-that-make-your-day-more-productive":{category:"Lifestyle",title:"Small habits that make your day more productive",excerpt:"Practical ideas for routines, focus, travel and modern living.",body:["Productivity does not require a complicated system. A short daily plan, fewer interruptions, and clear breaks can make work feel more manageable.","Choose one small habit to test this week. Keep it realistic, notice what helps, and adjust the routine to fit your schedule."]},
"beautiful-places-worth-adding-to-your-travel-list":{category:"Travel",title:"Beautiful places worth adding to your travel list",excerpt:"Destination inspiration, planning tips and memorable experiences.",body:["A memorable trip can come from scenery, local food, culture, or simply having time to explore at your own pace.","Before booking, check current entry requirements, seasonal conditions, transport, and local guidance. Build a flexible itinerary rather than filling every hour."]},
"what-people-are-watching-sharing-and-talking-about":{category:"Entertainment",title:"What people are watching, sharing and talking about",excerpt:"Trending entertainment, social moments and digital culture.",body:["Entertainment trends travel quickly across streaming platforms and social feeds. What is popular can vary by region, language, and platform.","Use recommendations as a starting point, then check the title, release details, and availability on the service you use."]},
"useful-online-tools-you-can-use-for-free":{category:"Guides",title:"Useful online tools you can use for free",excerpt:"Quick guides and practical tools for everyday digital tasks.",body:["Online utilities can help with common tasks such as resizing images, counting words, creating QR codes, and organizing text.","Choose reputable tools, avoid uploading sensitive files to services you do not trust, and review whether a tool processes information locally or on a server."]}
};
export function generateStaticParams(){return Object.keys(stories).map(slug=>({slug}));}
export default async function StoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const story=stories[slug];if(!story)return <main className="infoPage"><a href="/">← AdPage Builder</a><h1>Story not found</h1><p>This story may have moved. Browse the article library for more reads.</p><a href="/articles">Browse articles →</a></main>;return <main className="infoPage"><a href="/">← AdPage Builder</a><p className="eyebrow">{story.category} · AdPage Builder</p><h1>{story.title}</h1><p>{story.excerpt}</p><hr/><div>{story.body.map((p,i)=><p key={i}>{p}</p>)}</div><p><a href="/articles">Explore more articles →</a></p></main>}